/* CUSTOMIZER */
export const ADD_COSTOMIZER = "ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS = "ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIX_BACKGROUND_LAYOUT = "ADD_MIX_BACKGROUND_LAYOUT";
export const ROUTER_ANIMATION = "ROUTER_ANIMATION";

export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_FOLDER_FAIL = "CREATE_FOLDER_FAIL";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const GET_FOLDER = "GET_FOLDER";
export const GET_FOLDER_FAIL = "GET_FOLDER_FAIL";
export const GET_FOLDER_SUCCESS = "GET_FOLDER_SUCCESS";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const FAVORITE_FOLDER = "FAVORITE_FOLDER";
export const CHANGE_PARENT_ID = "CHANGE_PARENT_ID";
export const FAVORITE_FOLDER_OK = "FAVORITE_FOLDER_OK";
// export const CHANGE_PARENT_ID = "CHANGE_PARENT_ID";
